codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
    patch:
      default:
        target: auto
        threshold: 1%
        base: auto

comment:
  layout: "reach,diff,flags,tree,files"
  behavior: default
  require_changes: no
  require_base: no
  require_head: yes

ignore:
  - "test/**/*"
  - "dist/**/*"
  - "**/*.test.ts"
  - "**/*.config.*"
